Undefined behaviour if list length is 0 UwU
clibs/list pull request #35
Opened 2022-07-09 02:03 UTC by NickWilde263

Occurs when `list_destroy` on empty list

`0 - 1` at `len--` expression cant be represented as `unsigned int`

2022-07-09 02:25 UTC, diasbruno commented on src/list.c
> +  while (len > 0 && len--) {
```suggestion
  while (len-- >= 0) {
```
maybe?

2022-07-09 02:28 UTC, diasbruno commented on src/list.c
> +  while (len > 0 && len--) {
nah...

2022-07-09 02:31 UTC, NickWilde263 commented
@diasbruno did you just delete your suggestion saw it in notification but cant find it anywhere here?

2022-07-09 02:40 UTC, NickWilde263 commented
ye that also work

2022-07-09 02:42 UTC, diasbruno commented
The patch is ok. I thought it would miss the index `0`.

2022-07-09 02:42 UTC, diasbruno approved these changes

2022-07-09 02:47 UTC, NickWilde263 commented
> The patch is ok. I thought it would miss the index `0`.

you're confusing length with indexing?

2022-07-09 02:47 UTC, diasbruno commented
There is only one place that uses the `len` value. Maybe we can just change the `unsigned int` on `list_destroy`.

2022-07-09 02:51 UTC, NickWilde263 commented
cast it to `int` in `list_destroy` then use it?

2022-07-09 02:58 UTC, NickWilde263 commented
downcasting work perfectly as long there is nobody have list size of over 2 billions entries

2022-07-09 03:01 UTC, NickWilde263 commented
but its better to change the `len` to `int`  instead downcasting :3

2022-07-11 13:31 UTC, stephenmathieson requested changes
Please add a test for this.

2022-07-11 13:39 UTC, NickWilde263 commented
![Screenshot_2022-07-11_203547](https://user-images.githubusercontent.com/67861857/178277285-4da932e6-3636-4b8a-aaab-4d1438e25a2c.png)

@stephenmathieson did you request this change? (that was i did previously)

2022-07-11 13:40 UTC, NickWilde263 commented
![Screenshot_2022-07-11_203547](https://user-images.githubusercontent.com/67861857/178277515-4fa8aa04-045d-46e8-a979-28040b556cb9.png)

2022-07-11 13:43 UTC, stephenmathieson commented
No, I requested a test proving this change fixes something.

2022-07-11 13:48 UTC, NickWilde263 commented
> No, I requested a test proving this change fixes something.

it fixes undefined behaviour

2022-07-11 14:21 UTC, stephenmathieson commented
Please add an automated test to `test.c`.

2022-07-11 23:35 UTC, NickWilde263 commented
done adding test (need `-fsanitize=undefined` to show what this pull request trying to fix)

2022-07-12 15:04 UTC, NickWilde263 commented on test.c
> +test_list_empty_list_destroy() {
you need `-fsanitize=undefined` to see it

2022-07-12 15:15 UTC, diasbruno commented on test.c
> +test_list_empty_list_destroy() {
What @stephenmathieson means is that you need to write a test that trigger the UB. 

But it seems that the behavior is actually correct.
`while (len--)` will only decrement `len` after the while condition, so `while (0--)` should stop the loop. The problem would be if `len` is used outside of the loop.

Perhaps a false positive?

2022-07-12 15:18 UTC, diasbruno reviewed
I don't know, but I think this is a false positive.

2022-07-12 17:02 UTC, stephenmathieson commented on test.c
> +test_list_empty_list_destroy() {
Even with `-fsanitize=undefined` / `-fsanitize=unsigned-integer-overflow`, the test passes on the `master` branch.

```diff
diff --git a/Makefile b/Makefile
index 6f3fad7..20f9fd9 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@ AR ?= ar
 CC ?= gcc
 PREFIX ?= /usr/local
 
-CFLAGS = -O3 -std=c99 -Wall -Wextra -Ideps
+CFLAGS = -O3 -std=c99 -Wall -Wextra -Ideps -fsanitize=unsigned-integer-overflow
 
 SRCS = src/list.c \
 		   src/list_node.c \
```

```
➜  list git:(master) ✗ make test

list_t: 40
list_node_t: 24
list_iterator_t: 16

... list_node_new
... list_rpush
... list_lpush
... list_find
... list_at
... list_remove
... list_rpop
... list_lpop
... list_destroy
... list_empty_list_destroy
... list_iterator_t
... 100%
```

2022-07-12 23:37 UTC, NickWilde263 commented on test.c
> +test_list_empty_list_destroy() {
you're suppose to use both flag at same time (and on the linker also)

2022-11-06 13:49 UTC, closed without merging